# Dev settings, mainly mapping local volumes for fast code updates
# Make sure to `npm run watch` on host machine to get builds

version: "3"

services:
  host:
    build:
      context: ./host
      dockerfile: Dockerfile
    volumes:
      - ./host/bin:/bin-holo
      - ./host/webserver:/root/webserver  # be sure to `npm run watch` to get build updates
      - ./host/hosting-happs:/hosting-happs  # be sure to `npm run watch` to get build updates
      - ./host/hosted-happs:/hosted-happs
